controllerManager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: niteshmore22/cve-operator
      tag: latest
      pullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: base64_encoded_dockerconfigjson

configMap:
  kafka_topic: cve
  kafka_brokers: 
    - cve-kafka-controller-0.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092
    - cve-kafka-controller-1.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092
    - cve-kafka-controller-2.cve-kafka-controller-headless.cve-kafka.svc.cluster.local:9092
secrets:
  type: Opaque
  kafka_username: kafka_username
  kafka_password: kafka_password

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

GitHubReleasesMonitor:
  url: https://github.com/CVEProject/cvelistV5/releases
  monitorFrom: "2024-08-02"
  helmReleaseName: cve-operator
  githubReleaseJobConfig:
    image: niteshmore22/webapp-cve-processor:latest
    imagePullPolicy: Always
    backoffLimit: 3
    ttlSecondsAfterFinished: 100

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80

pdb:
  create: true
  maxUnavailable: 1