apiVersion: cve-producer.archops.com/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
  {{- include "cve-operator.labels" . | nindent 4 }}
  name: {{ include "cve-operator.fullname" . }}-githubreleases-monitor
  namespace: {{ .Release.Namespace }}
spec:
  url: {{ .Values.GitHubReleasesMonitor.url }}
  monitorFrom: {{ .Values.GitHubReleasesMonitor.monitorFrom | quote}}
  helmReleaseName: {{ .Release.Name}}
  githubReleaseJobConfig:
    image: {{ .Values.GitHubReleasesMonitor.githubReleaseJobConfig.image }}
    imagePullPolicy: {{ .Values.GitHubReleasesMonitor.githubReleaseJobConfig.imagePullPolicy }}
    backoffLimit: {{ .Values.GitHubReleasesMonitor.githubReleaseJobConfig.backoffLimit}}