apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: {{ .Values.imagePullSecrets.type }}