---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limitrange
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - default:
        memory: {{ .Values.resources.limits.memory }}
        cpu: {{ .Values.resources.limits.cpu | quote}}
      defaultRequest:
        memory: {{ .Values.resources.requests.memory }}
        cpu: {{ .Values.resources.requests.cpu | quote }}
      type: Container