apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cve-operator.fullname" . }}-metrics-reader
  labels:
  {{- include "cve-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get