apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cve-operator.fullname" . }}-metrics-auth-role
  labels:
    {{- include "cve-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cve-operator.fullname" . }}-metrics-auth-rolebinding
  labels:
    {{- include "cve-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cve-operator.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "cve-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
