# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: {{.Values.secrets.type}}
data:
  {{- include "cve-operator.secrets" .| indent 2}}